### ISSUE TITLE
Release rnaturalearthdata 1.0.0

### ISSUE THREAD

**Issue by PMassicotte** [ropensci/rnaturalearthdata#11]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_rnaturalearthdata.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] Update `cran-comments.md`
* [x] `git push`
* [x] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] Add preemptive link to blog post in pkgdown news menu
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`
* [ ] Finish blog post
* [ ] Tweet

**Comment by PMassicotte** [comment]
@andysouth @mps9506 

I have finalized the release of v1.0.0, which discontinues support for the `sp` object in favor of `sf` to align with the latest version of `rnaturalearth` on CRAN. Unfortunately, as I am not the `rnaturalearthdata` maintainer, I cannot submit it to CRAN or run `devtools::check_win_devel()`. Do you agree with this change, and if so, could you please handle the submission process?

Cheers,
Phil

**Comment by mps9506** [comment]
@PMassicotte thanks for making these needed updates. @andysouth will have to make the submission unless we make a special request to CRAN.

**Comment by arnejohannesholmin** [comment]
Hi, Thanks for this package. I wanted to if there is a plan to submit the latest version (1.0.0) to CRAN any time soon? We are planning a release of a fisheries research software (https://github.com/StoXProject) where we are removing all dependency on sp, but we import rnaturalearthdata.

**Comment by PMassicotte** [comment]
Hi @arnejohannesholmin.

We are waiting for @andysouth because we do not have the right to submit it to CRAN  :) I think he might missed the notification. I will try to contact him over email.

**Comment by Luigi-Annic** [comment]
Hi!

Many thanks for this package and for this update, which proved very useful.
Is there any news about submitting the version 1.0.0 to CRAN?
Do you plan to make it available on CRAN by the end of February?
Just to know whether to use this version or the previous one for my program.

Thank you!

**Comment by andysouth** [comment]
Hi @PMassicotte @mps9506 
Many thanks for your work on this and apologies for the delay on my part.
I have just replied to CRAN accepting the submission and maintainer change.
If you need me to do anything else, let me know and I will be prompter !
Best wishes,
Andy

**Comment by PMassicotte** [comment]
Absolutely no problem @andysouth ! Thank you
