### ISSUE TITLE
Is there a description of the non-polygon data provided through rnaturalearthdata?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/rnaturalearthdata#2]
This question was posted by @JanDuo in the rOpenSci public forum:
https://discuss.ropensci.org/t/is-there-a-description-of-the-non-polygon-data-provided-through-rnaturalearthdata/2505

**Comment by andysouth** [comment]
Thanks @JanDuo @stefaniebutland 

Good question.

In general rnaturalearth relies on what is provided by www.naturalearthdata.com.

In this case there seems to be relatively little documentation e.g. https://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/

Specifically about income group I suspect it follows something like this : https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups
```
nec <- ne_countries(returnclass='sf')
unique(nec$income_grp)
```
[1] "5. Low income"           "3. Upper middle income"  "4. Lower middle income" 
[4] "2. High income: nonOECD" "1. High income: OECD"   

Apologies taken me a little while to reply, also aware that I could do with finding some time to give rnaturalearth a little love.

Metaquestion @stefaniebutland, is it better to answer here in the issue or in the forum or both :-) ?

**Comment by JanDuo** [comment]
Thanks @andysouth, I understand it's not clearcut to you as well. The worldbank has quite some different definitions compared to https://www.gapminder.org/?s=income+level.
But there is an excelsheet with data worth checking (by me): http://databank.worldbank.org/data/download/site-content/OGHIST.xls
Thanks for pointing me in this direction!

**Comment by stefaniebutland** [comment]
@andysouth 
>  is it better to answer here in the issue or in the forum or both :-) ?

The best place is wherever it's best for you :-). I added a link to your response into the forum thread so folks can see that you answered.

**Comment by JanDuo** [comment]
Hi @andysouth , after a second look these definitions are not that different from one another. The worldbank uses figures for a yearly income and gapminder for a daily income.
Gapminder uses $2, $8 and $32 as separators between the 4 groups. If I change the figures of the Worldbank of 2019 into daily income (and round to whole numbers) it shows $3, $11 and $34.

**Comment by andysouth** [comment]
Thanks @JanDuo @stefaniebutland, closing this one now :-)
